name: "IR-Trigger USB Daemon"
description: "Reads AD00020P USB IR Receiver and sends data to Home Assistant IR-Trigger Integration via Webhook."
version: "1.0.1"
slug: "ir_trigger_daemon"
init: false
arch:
  - aarch64
  - amd64
  - armv7
  - i386
startup: application
boot: auto
map:
  - config:rw
options:
  webhook_url: "http://homeassistant:8123/api/webhook/ir_trigger_webhook"
  receiver_name: "HAOS_AD00020P"
schema:
  webhook_url: url
  receiver_name: str
usb: true
udev: true
apparmor: false
full_access: true
