[env:m5stick-s3]
platform = espressif32
board = esp32-s3-devkitc-1 ; Generic S3 board. M5Unified will auto-detect the specific M5 device.
framework = arduino
monitor_speed = 115200
board_build.mcu = esp32s3
board_build.arduino.memory_type = qio_opi
lib_deps =
    m5stack/M5Unified
    crankyoldgit/IRremoteESP8266
    me-no-dev/ESPAsyncWebServer
    bblanchon/ArduinoJson
extra_configs = secrets.ini

build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D WIFI_SSID='"${secrets.wifi_ssid}"'
    -D WIFI_PASSWORD='"${secrets.wifi_password}"'
    -D BOARD_HAS_PSRAM