[env:m5stick-s3]
platform = espressif32
board = esp32-s3-devkitc-1 ; Generic S3 board. M5Unified will auto-detect the specific M5 device.
framework = arduino
monitor_speed = 115200
board_build.mcu = esp32s3
lib_deps =
    m5stack/M5Unified@^0.1.14
