DOMAIN = "ir_trigger"
EVENT_IR_RECEIVED = "ir_trigger_received"
SERVICE_RELOAD = "reload"

DICT_FILE_NAME = "IR-Trigger.yaml"

CONF_RECEIVER = "receiver"
CONF_CODE = "code"

CONF_MODE_ENTITY = "mode_entity"
CONF_TRANSMITTERS = "transmitters"
CONF_DEVICES = "devices"
CONF_MODES = "modes"

CONF_TYPE = "type"
CONF_INDEX = "index"
CONF_ENTITY_ID = "entity_id"
CONF_TRANSMITTER = "transmitter"
CONF_BUTTONS = "buttons"
CONF_BIND = "bind"
CONF_REMAP = "remap"
CONF_SOURCE = "source"
CONF_TARGET = "target"
CONF_SERVICE = "service"
CONF_DATA = "data"
CONF_NAME = "name"
CONF_LOCAL_RECEIVERS = "local_receivers"
CONF_REPEAT = "repeat"
CONF_FORCE_AEHA_TX = "force_aeha_tx"
CONF_DOMAIN = "domain"
CONF_MAPPING = "mapping"

ATTR_RECEIVER = "receiver"
ATTR_DEVICE = "device"
ATTR_BUTTON = "button"
ATTR_CODE = "code"
ATTR_VIA_DEVICE = "via_device"

SIGNAL_NEW_RECEIVER = f"{DOMAIN}_new_receiver"
SIGNAL_UPDATE_SENSOR = f"{DOMAIN}_update_sensor"
SIGNAL_LOAD_COMPLETE = f"{DOMAIN}_load_complete"
